// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package trackem is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	EmailTracker
*/
package trackem

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmailTracker struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	FromAddr string `protobuf:"bytes,2,opt,name=from_addr,json=fromAddr" json:"from_addr,omitempty"`
	ToAddrs  string `protobuf:"bytes,3,opt,name=to_addrs,json=toAddrs" json:"to_addrs,omitempty"`
	Subject  string `protobuf:"bytes,4,opt,name=subject" json:"subject,omitempty"`
	Gets     int64  `protobuf:"varint,5,opt,name=gets" json:"gets,omitempty"`
}

func (m *EmailTracker) Reset()                    { *m = EmailTracker{} }
func (m *EmailTracker) String() string            { return proto.CompactTextString(m) }
func (*EmailTracker) ProtoMessage()               {}
func (*EmailTracker) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EmailTracker) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EmailTracker) GetFromAddr() string {
	if m != nil {
		return m.FromAddr
	}
	return ""
}

func (m *EmailTracker) GetToAddrs() string {
	if m != nil {
		return m.ToAddrs
	}
	return ""
}

func (m *EmailTracker) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *EmailTracker) GetGets() int64 {
	if m != nil {
		return m.Gets
	}
	return 0
}

func init() {
	proto.RegisterType((*EmailTracker)(nil), "trackem.EmailTracker")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0xce, 0x31, 0x0e, 0xc2, 0x30,
	0x0c, 0x85, 0x61, 0xa5, 0x2d, 0xb4, 0xb5, 0x80, 0xc1, 0x53, 0x10, 0x4b, 0xc5, 0xd4, 0x89, 0x85,
	0x13, 0x30, 0x70, 0x81, 0x8a, 0x1d, 0xb5, 0x75, 0x40, 0x01, 0xa2, 0x20, 0xc7, 0x70, 0x02, 0x0e,
	0x8e, 0x6a, 0xd8, 0xec, 0xff, 0x5b, 0x1e, 0x2c, 0x93, 0xe3, 0xb7, 0x1f, 0xdd, 0xee, 0xc9, 0x51,
	0x22, 0x96, 0xc2, 0xfd, 0x78, 0x77, 0x61, 0xfb, 0x31, 0xb0, 0x38, 0x86, 0xde, 0x3f, 0x4e, 0x1a,
	0x18, 0x57, 0x90, 0x79, 0xb2, 0xa6, 0x31, 0x6d, 0xdd, 0x65, 0x9e, 0x70, 0x03, 0xf5, 0x85, 0x63,
	0x38, 0xf7, 0x44, 0x6c, 0x33, 0xcd, 0xd5, 0x14, 0x0e, 0x44, 0x8c, 0x6b, 0xa8, 0x24, 0x2a, 0x25,
	0x9b, 0xab, 0x95, 0x12, 0x27, 0x49, 0x68, 0xa1, 0x4c, 0xaf, 0xe1, 0xe6, 0x46, 0xb1, 0xc5, 0x4f,
	0xfe, 0x2f, 0x22, 0x14, 0x57, 0x27, 0xc9, 0xce, 0x1a, 0xd3, 0xe6, 0x9d, 0xde, 0xc3, 0x5c, 0x67,
	0xed, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x93, 0xa4, 0xa9, 0xbf, 0xa7, 0x00, 0x00, 0x00,
}
